//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTitulo.Models
{
    using System;
   
    
    public partial class Asesor
    {
        
        public Asesor()
        {
            
        }

        public int Id { get; set; }
        public int Rut { get; set; }
        public byte[] Foto { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Sexo { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Nacionalidad { get; set; }
        public int IdComuna { get; set; }
        public decimal ValorHora { get; set; }
        public string Comentario { get; set; }
        public int Fono { get; set; }
        public string Correo { get; set; }
        public string Contrasena { get; set; }

        public virtual Comuna Comuna { get; set; }
    }
}
