//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTitulo.Models
{
    using System;
    
    
    public partial class Servicio
    {
        
        public Servicio()
        {
            
        }
    
        public int Id { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdAsesor { get; set; }
        public Nullable<int> IdDireccion { get; set; }
        public System.DateTime Fecha { get; set; }
        public int CantidadHoras { get; set; }
        public System.TimeSpan HoraInicio { get; set; }
        public System.TimeSpan HoraTermino { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Notificacion { get; set; }
        public string FormaPago { get; set; }
        public int Estado { get; set; }
    
      
       
        
    }
}
